import turtle
turtle.bgcolor("black")
# Begin!
t = turtle.Turtle()
t.color("yellow")
t.fillcolor("yellow")
t.penup()
t.left(90)
t.forward(20)
t.right(90)
t.forward(100)
t.pendown()
t.begin_fill()
t.circle(30)
t.end_fill()
#Drawing Star-1
t.penup()
t.left(90)
t.forward(70)
t.color("white")
t.fillcolor("white")
t.pendown()
t.begin_fill()
for i in range(5):
    t.forward(40)
    t.left(144)
t.end_fill()
#Drawing Star-2
t.penup()
t.left(45)
t.forward(80)
t.color("white")
t.fillcolor("white")
t.pendown()
t.begin_fill()
for i in range(5):
    t.forward(30)
    t.left(144)
t.end_fill()
t.hideturtle()
#Drawing Star-3
t.penup()
t.left(135)
t.forward(80)
t.color("white")
t.fillcolor("white")
t.pendown()
t.begin_fill()
for i in range(5):
    t.forward(20)
    t.left(144)
t.end_fill()
#Dashed line
t.penup()
t.right(45)
t.forward(200)
t.color("white")
t.pendown()
t.left(135)
for i in range(15):
    t.forward(10)
    t.penup()
    t.forward(20)
    t.pendown()
turtle.done()