import turtle
import time
# Function to draw the traffic light frame
#def draw_traffic_light_frame():
turtle.penup()
turtle.goto(-35, -100)
turtle.pendown()
turtle.color("dark grey")
turtle.begin_fill()
for i in range(2):
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(200)
    turtle.left(90)
turtle.end_fill()
turtle.width(15)
turtle.color('black')
turtle.up()
turtle.forward(50)
turtle.right(90)
turtle.down()
turtle.forward(200)
turtle.up()
turtle.backward(200)
turtle.right(90)
turtle.forward(50)
turtle.left(180)
turtle.down()
turtle.width(0)
turtle.color('dark grey')
turtle.hideturtle()
#draw_traffic_light_frame()
while True:
    # Create a turtle for drawing
    t1 = turtle.Turtle()
    t1.penup()
    t1.goto(15,30)
    t1.pendown()
    t1.speed(10)
    t1.hideturtle()
    t1.circle(20)
    t2 = turtle.Turtle()
    t2.penup()
    t2.goto(15,-30)
    t2.pendown()
    t2.speed(10)
    t2.hideturtle()
    t2.circle(20)
    t3 = turtle.Turtle()
    t3.penup()
    t3.goto(15,-90)
    t3.pendown()
    t3.speed(10)
    t3.hideturtle()
    t3.circle(20)
    t1.fillcolor("red")
    t1.begin_fill()
    t1.circle(20)
    t1.end_fill()
    time.sleep(0.01)
    t1.fillcolor("white")
    t1.begin_fill()
    t1.circle(20)
    t1.end_fill()
    time.sleep(0.01)
    t2.fillcolor("orange")
    t2.begin_fill()
    t2.circle(20)
    t2.end_fill()
    time.sleep(0.01)
    t2.fillcolor("white")
    t2.begin_fill()
    t2.circle(20)
    t2.end_fill()
    time.sleep(0.01)
    t3.fillcolor("green")
    t3.begin_fill()
    t3.circle(20)
    t3.end_fill()
    time.sleep(0.01)
    t3.fillcolor("white")
    t3.begin_fill()
    t3.circle(20)
    t3.end_fill()
    #draw_pole()
    time.sleep(0.01)
turtle.done()